# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 02:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='application_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
