# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_savejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='subject',
            field=models.CharField(default='Gourav Pathela', max_length=100),
            preserve_default=False,
        ),
    ]
