# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-21 07:46
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobstatus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_application_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('message', models.TextField(max_length=1000)),
                ('sent_on', models.DateTimeField(default=datetime.datetime.now)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Job')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Applicant', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='JobOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
