# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 02:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20170419_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('company_url', models.URLField()),
                ('official_email', models.EmailField(max_length=254)),
                ('company_facebook_page', models.URLField()),
                ('company_google_page', models.URLField()),
                ('company_linkedin_page', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
