# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_employerdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='mobile',
            field=models.IntegerField(blank=True),
        ),
    ]
