# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 06:56
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField(max_length=1000)),
                ('location', models.CharField(max_length=100)),
                ('remuneration', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('activate_date', models.DateField(default=datetime.date.today)),
                ('post_date', models.DateField(default=datetime.date.today)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
